export const PLAYER_NAME_MAP: Record<string, string> = {
  // Gujarat Lions vs KKR (2017)
  "JJ Roy": "Jason Roy",
  "BB McCullum": "Brendon McCullum",
  "SK Raina": "Suresh Raina",
  "AJ Finch": "Aaron Finch",
  "KD Karthik": "Dinesh Karthik",
  "DR Smith": "Dwayne Smith",
  "P Kumar": "Praveen Kumar",
  "DS Kulkarni": "Dhawal Kulkarni",
  "SB Jakati": "Shadab Jakati",
  "S Kaushik": "Shivil Kaushik",
  "G Gambhir": "Gautam Gambhir",
  "CA Lynn": "Chris Lynn",
  "RV Uthappa": "Robin Uthappa",
  "MK Pandey": "Manish Pandey",
  "YK Pathan": "Yusuf Pathan",
  "SA Yadav": "Suryakumar Yadav",
  "CR Woakes": "Chris Woakes",
  "SP Narine": "Sunil Narine",
  "Kuldeep Yadav": "Kuldeep Yadav",
  "TA Boult": "Trent Boult",
  "PP Chawla": "Piyush Chawla",
  "C de Grandhomme": "Colin de Grandhomme",
  "NM Coulter-Nile": "Nathan Coulter-Nile",
  "UT Yadav": "Umesh Yadav",
  "CJ Anderson": "Corey Anderson",
  "LH Ferguson": "Lockie Ferguson",
  "AD Nath": "Akshdeep Nath",
  "Ishan Kishan": "Ishan Kishan",
  "Basil Thampi": "Basil Thampi",
  "RA Jadeja": "Ravindra Jadeja",
  "JP Faulkner": "James Faulkner",
  
  // RCB vs SRH (2017)
  "CH Gayle": "Chris Gayle",
  "Mandeep Singh": "Mandeep Singh",
  "TM Head": "Travis Head",
  "KM Jadhav": "Kedar Jadhav",
  "SR Watson": "Shane Watson",
  "Sachin Baby": "Sachin Baby",
  "STR Binny": "Stuart Binny",
  "S Aravind": "Sreenath Aravind",
  "TS Mills": "Tymal Mills",
  "YS Chahal": "Yuzvendra Chahal",
  "A Choudhary": "Aniket Choudhary",
  "DA Warner": "David Warner",
  "S Dhawan": "Shikhar Dhawan",
  "MC Henriques": "Moises Henriques",
  "Yuvraj Singh": "Yuvraj Singh",
  "DJ Hooda": "Deepak Hooda",
  "BCJ Cutting": "Ben Cutting",
  "NV Ojha": "Naman Ojha",
  "Bipul Sharma": "Bipul Sharma",
  "B Kumar": "Bhuvneshwar Kumar",
  "A Nehra": "Ashish Nehra",
  "Rashid Khan": "Rashid Khan",

  // Modern prominent
  "V Kohli": "Virat Kohli",
  "RG Sharma": "Rohit Sharma",
  "MS Dhoni": "MS Dhoni",
  "AB de Villiers": "AB de Villiers",
  "KS Williamson": "Kane Williamson",
  "SPD Smith": "Steve Smith",
  "JE Root": "Joe Root",
  "BA Stokes": "Ben Stokes",
  "PJ Cummins": "Pat Cummins",
  "MA Starc": "Mitchell Starc",
  "JJ Bumrah": "Jasprit Bumrah",
  "HH Pandya": "Hardik Pandya",
  "KL Rahul": "KL Rahul",
  "RR Pant": "Rishabh Pant",
  "JC Buttler": "Jos Buttler",
  "Q de Kock": "Quinton de Kock",
  "K Rabada": "Kagiso Rabada",
  "F du Plessis": "Faf du Plessis",
  "AD Russell": "Andre Russell",
  "GJ Maxwell": "Glenn Maxwell",
  "KA Pollard": "Kieron Pollard",
  "Mohammed Siraj": "Mohammed Siraj",
  "Mohammed Shami": "Mohammed Shami",
  "R Ashwin": "Ravichandran Ashwin",
  "Shubman Gill": "Shubman Gill",
  "SS Iyer": "Shreyas Iyer",
  "R Gaikwad": "Ruturaj Gaikwad",
  "YBK Jaiswal": "Yashasvi Jaiswal",
  "DP Conway": "Devon Conway",
  "MM Ali": "Moeen Ali",
  "MP Stoinis": "Marcus Stoinis",
  "LH Livingstone": "Liam Livingstone",
  "N Pooran": "Nicholas Pooran",
  "SO Hetmyer": "Shimron Hetmyer"
};

export function formatPlayerName(name: string): string {
  if (!name) return "";
  const trimmed = name.trim();
  
  if (PLAYER_NAME_MAP[trimmed]) {
      return PLAYER_NAME_MAP[trimmed];
  }

  return trimmed;
}
